CMakeLists.txt
README.md
libphx/CMakeLists.txt
libphx/src/Shader.cpp
script/App/GenTex2D.lua

This PR makes a few changes:
* Fix the lt64/libphx64 suffixes when building under release/relwithdebinfo/minsizerel. There should only be a d suffix with the debug build.
* Ensure that the debugging working directory for Visual Studio is set correctly by CMake.
* Add some instructions on how to debug with VS.
* Fix a crash in `Shader_Create`
* Fix a resource loading issue in `GenTex2D.lua`

Fix Visual Studio Debugging

---

libphx/include/Sound.h
libphx/script/ffi/Sound.lua
libphx/src/Sound.cpp
script/States/App/FMODTest.lua

Basic support for fading sound in & out - mainly to support switching between music soundtracks
- Sound_FadeIn(seconds)
- Sound_FadeOut(seconds)
- bool Sound_IsAudible()
Fade in can be used to start playing a sound.
A faded out sound is paused and will continue from that point when faded in (could use Rewind())
An in progress fade in/out is unaffected by these calls.
Use IsAudible() to check if a sound is paused or not. IsPlaying() means that the sound is active - almost always, and IsPaused() does not exist but would make a sound inactive. The audio subsystem will only update **active** sounds per frame
Pre-empted the addition of a second music file by @Flatfingers so that FMODTest.lua could test fading between songs. Use left mouse to start a 5 second crossfade (sounds horrible).

Basic sound fader support

---

res/shader/fragment/ui/triangle.glsl
script/Systems/Overlay/HUD.lua

UI triangle shaders are 2D, so swizzle vec3s to vec2s
Use triangle in HUD targetter

Fix shader crash when HUD targetter tries to draw direction arrow

---

.gitignore
libphx/include/Button.h
libphx/script/ffi/Button.lua
libphx/src/Button.cpp
libphx/src/Input.cpp
script/States/Application.lua

This PR addresses Issue #36 only.
Changes:
- Add System window input events to detect mouse enter/leave
- Allow mouse inputs when leaving the window for drag/resize etc
- Auto-pause game when leaving the window
Observations:
- The existing window resize is only a crop.
- Whilst paused, mouse movement within the window still moves turrets
- Whilst paused, mouse-left-click still starts a fire sequence

Add support for draggable/resizable game window [PHX REBUILD REQUIRED]

---

script/Config/App.lua
script/GameObjects/Actions/Attack.lua
script/GameObjects/Components/Ship/Capacitor.lua
script/GameObjects/Entities/Ship/Turret.lua
script/States/App/LTheoryRedux.lua
script/States/Application.lua
script/Systems/Controls/Controls/DockControl.lua
script/Systems/Menus/MainMenu.lua
script/Systems/Overlay/HUD.lua
script/UI/DrawEx.lua

* Made a first start at enabling Settings. Several of the values stored in user.ini can now be adjusted in Settings. Note that although Settings can be displayed from both the Main Menu and in Flight mode, ship generation settings are only displayed from the Main Menu.
* Hooked up the previously unused Capacitor feature to ships. Now energy weapons (currently only Pulse Turrets) draw power from the ship's capacitor, and can only fire as long as there's energy left (which recharges automatically). For the player's ship, the current capacitor energy remaining is now displayed in the HUD.
* Power Allocation settings now have an "overcharge" value. There's no active functionality here yet -- this is just enhancing the HUD to show when a ship's component is overcharged.

Settings / Energy Capacitor / Overcharge

---

libphx/src/Lua.rs
libphx/src/Profiler.rs
libphx/src/Signal.rs

The previous code was using some buggy linked list which clearly wasn't adding signal handlers properly. I rewrote it properly using real Rust idioms. This fixes the crash when profiling the code by pressing F10 twice.

Rewrite the signal handler code using safe Rust HashMaps

---

Cargo.lock
libphx/Cargo.toml

**LuaJit 5.2 extensions:**
- goto is a keyword and not a valid variable name anymore.
-  break can be placed anywhere. Empty statements (;;) are allowed.
- __lt, __le are invoked for mixed types.
- __len for tables. rawlen() library function.
- pairs() and ipairs() check for __pairs and __ipairs.
- coroutine.running() returns two results.
- table.pack() and table.unpack() (same as unpack()).
- io.write() and file:write() return file handle instead of true.
- os.execute() and pipe:close() return detailed exit status.
- debug.setmetatable() returns object.
- debug.getuservalue() and debug.setuservalue().
- remove math.mod(), string.gfind().
see: https://luajit.org/extensions.html
also run cargo update / update .lock
no code breaking apparant.

feature: enable luajit lua 5.2 partial compability

---

script/Config/App.lua
script/Enums/EmissionEnums.lua
script/GameObjects/Actions/Think.lua
script/GameObjects/Entities/Test/System.lua
script/Systems/Overlay/HUD.lua

* The player ship's sensors now have two modes: 1) display frequency info about a targeted object (if within range and inside the sensor cone), and 2) display frequency info for all objects in range and inside the sensor cone.
* System.lua got a minor update to add object lists for Stars (not yet implemented) and Planets; to provide helper functions for returning System object lists; and to slightly rearrange the ordering of helper function definitions to be a bit more logical.

Add untargeted sensor display

---

script/Systems/Controls/Controls/MasterControl.lua

When the panel is disabled, MasterControl#onInput assumed that the activeControlSet was not nil.
If autopilot on, there was no flight control prior to panel open, so self.activeControlSet is nil and a crash occurs.

Check activeControlSet not nil before access.

---

Cargo.toml

Overlooked workspace license that we didn´t change yet

Workspace License

---

engine/lib/luajit-ffi-gen/src/args/bind_args.rs
engine/lib/luajit-ffi-gen/src/impl_item/parse.rs
engine/lib/phx/src/input/input_bindings.rs
engine/lib/phx/src/lua/lua_scheduler.rs
engine/lib/phx/src/math/rng.rs
engine/lib/phx/src/physics/physics.rs
engine/lib/phx/src/physics/rigid_body.rs
engine/lib/phx/src/physics/trigger.rs
engine/lib/phx/src/system/hash_map.rs
engine/lib/phx/src/system/profiler.rs
engine/lib/phx/src/system/str_map.rs

The updated  Rust compiler generates a bunch of new warnings due to duplicate symbols, so this PR cleans them up.

Remove warnings after updating to Rust 1.74

---

engine/lib/luajit-ffi-gen/README.md
engine/lib/phx/src/math/box3.rs
engine/lib/phx/src/math/math.rs
engine/lib/phx/src/math/matrix.rs
engine/lib/phx/src/math/mod.rs
engine/lib/phx/src/math/quat.rs
engine/lib/phx/src/physics/rigid_body.rs
engine/lib/phx/src/render/gl_matrix.rs
engine/lib/phx/src/render/shader.rs
script/Systems/Overlay/GameView.lua

glam is a 3D math library we use in libphx for vectors. However, we're still using the original libphx matrix / quat math functions, and many of those are potentially hiding hidden bugs / inefficiencies / other issues, and are also unsafe as they rely on a lot of array indexing. It's also hard to maintain them without any unit tests, so this PR switches the implementation of them over to using glam equivalents, which are already maintained, fast and 100% tested.
The biggest notable semantic change is that matrices are now column-major (like OpenGL), rather then row-major (like Direct3D). This doesn't really change much in reality, because libphx was previously transposing it's row major matrices before passing them to shaders (which are column major), and now we just stop doing that and …

Reimplement Matrix and Quat using glam.

---

script/GameObjects/Entities/Ship/Thruster.lua

The thruster effect was displayed on the first person camera sometimes occluding it when flying backwards.

refactor: prevent thruster fx being rendered in first person

---

script/States/Application.lua

feature: add provisional background mode hints

---

script/Enums/GameStates.lua
script/States/App/LTheoryRedux.lua
script/Systems/Overlay/GameView.lua

smol provisional feature which adds a state inbetween the ingame and main menu state where you can randomly generate your player ship

feature: add ship creation "menu"

---

script/States/Application.lua

- Changes the kinda aggressive sounding `EXPERIMENTAL BUILD - NOT FINAL!` to `WORK IN PROGRESS` :D 
- Renders the build number / game version on the bottom left
- Makes the text a bit transparent
- Changes are for the upcoming nightly release change #180

Render build version & adjust WIP text

---

script/GameObjects/Entities/Ship/Thruster.lua
script/States/App/LTheoryRedux.lua
script/States/Application.lua
script/States/ApplicationBindings.lua
script/Systems/Controls/Bindings/ShipBindings.lua
script/Systems/SFX/MusicPlayer.lua
script/Systems/Universe/Universe.lua

1. Prevent crash in Thruster.lua when any ship (player or NPC) is destroyed. A test was added recently to Thruster:render() to not display thrusters if the player's ship was in first-person mode. This test was referencing a nil object when any ship is destroyed, causing a crash to desktop. This test has been temporarily commented out until it can be refined if necessary.
2. Prevent crash when "B" to spawn a new player ship is pressed more than one time. The recent addition to enable "B" to generate multiple Solo sized player ships before entering a game universe, and "F" to spawn the created player ship, worked only if "B" was pressed once. If "B" was pressed twice or more, then the ship was spawned, a hard crash would occur in the sensor display section of HUD.lua because the position of …

Three Fixes

---

.github/workflows/pr_build.yaml
.github/workflows/release_build.yaml
Cargo.lock
build.sh
engine/bin/ltr/Cargo.toml
engine/bin/ltr/src/main.rs
engine/lib/phx/src/engine/mod.rs
script/Config/Version.lua
script/Main.lua

- Print application versions and build timestamp at startup
- Compare Engine and script versions
- Run tests in CI

Various improvements for app startup

---

.github/workflows/release_build.yaml

- noticed that this happens yesterday if releasing as a prerelease

Ensure that release is not created as a draft

---

engine/lib/internal/src/memory.rs
engine/lib/luajit-ffi-gen/README.md
engine/lib/luajit-ffi-gen/src/args/bind_args.rs
engine/lib/luajit-ffi-gen/src/ffi_generator.rs
engine/lib/luajit-ffi-gen/src/impl_item/generate.rs
engine/lib/luajit-ffi-gen/src/impl_item/lua_ffi.rs
engine/lib/luajit-ffi-gen/src/impl_item/parse.rs
engine/lib/luajit-ffi-gen/src/impl_item/type_info.rs
engine/lib/luajit-ffi-gen/tests/test_impl.rs
engine/lib/phx/script/ffi_gen/Directory.lua

Out parameters are used quite often in the Physics code, so I decided to add support in luajit-ffi-gen rather than rewrite the Lua code.
This PR also fixes the annoying snake case warning generated when compiling `memory.rs`, and I fixed a few mismatches in the C FFI such as:
* When returning an option of a non-copyable type, like `Directory_Open`
* When returning a non-copyable type, the FFI was missing the `*`.
As both `as_ffi_string()` in `type_info.rs` and `wrap_type` in `generate.rs` are supposed to be equivalent to each other, I rewrote `as_ffi_string()` by taking the implementation of `wrap_type` and changing the Rust types to C. I find it much easier to follow now.
Generated `My_Struct.lua` from `test_impl.rs`, to show what the new features look like:
```lua
-- My_Struct …
```

Add support for out parameters, boxed types, and returning an mutable optional ref. Fix some mismatches in the C FFI.

---

engine/lib/phx/src/physics/physics.rs
engine/lib/phx/src/physics/trigger.rs

This can happen if a collider is removed between when the narrowphase is updated (during a physics tick) and when we look at the narrowphase's results, either through Trigger.GetContentsCount, or Physics.GetNextCollision.

Ignore stale colliders when looking at the narrowphase.

---

docs/GameControlKeys.txt
script/Config/UI/UIConfig.lua
script/Enums/HudEnums.lua
script/Systems/Overlay/HUD.lua
script/Systems/Universe/UniverseEconomy.lua
script/Types/GameState.lua
script/UI/DrawEx.lua

First draft of a tactical radar that displays nearby vessels (ships and stations).
For quick clarity, the initial version uses only the x (0 to infinity to 0 to -infinity to 0) and y (1 or -1) components of `self.gameView.camera:worldToNDC(object:getPos())` to position vessels on the radar. The y component ("up" or "down" relative to the player ship's facing) is not currently used. (This actually works pretty well -- try it!)
The Numpad1, Numpad2, and Numpad3 keys change the current range of the tactical radar among Close, Normal, and Distant.
Ship dots are small; station dots are large.
The color of radar dots are drawn according to the color returned by a Disposition check.
Bugs:
* Although the values returned from `worldToNDC()` can go as high as +/- infinity, they are cut off at 1.57 …

Initial version of the working tactical radar

---

Cargo.lock
engine/lib/phx/Cargo.toml
script/Init.lua

I forked glutin to incorporate a patch that makes it work correctly on macOS.
This should only be needed until we've moved to WGPU.
Also, JIT on macOS arm64 performs terribly. Due to some restrictions in the way LuaJIT currently works, the Lua code is constantly getting recompiled every time a function is executed, meaning that I was getting less than 1 FPS on my work machine (an M1 Max MBP).

Use fork of glutin that works correctly on macOS, and disable JIT on arm64 macs.

---

engine/lib/luajit-ffi-gen/src/ffi_generator.rs

When git checks out these files, they are checked out as CRLF. Then, when luajit-ffi-gen runs, they get replaced with LF and so git thinks the files have changed.

Generate meta files as CRLF on Windows.

---

.github/workflows/pr_build.yaml
.github/workflows/release_build.yaml

the macos-11 image was deprecated in January, and is apparently going through a brownout in late June: https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal

Update github actions runner to macos-12

---

engine/lib/luajit-ffi-gen/src/ffi_generator.rs
engine/lib/luajit-ffi-gen/src/impl_item/generate.rs
engine/lib/luajit-ffi-gen/src/impl_item/impl_info.rs
engine/lib/luajit-ffi-gen/src/impl_item/lua_ffi.rs
engine/lib/phx/script/ffi_gen/Time.lua
engine/lib/phx/src/audio/audio.rs
engine/lib/phx/src/physics/physics.rs
engine/lib/phx/src/render/bsp.rs

This was happening because the Time_Free method wasn't being generated correctly. We try to detect when a type needs a _Free method by checking to see if we have any methods that take `self` as the first argument. `Time` is quite unique in that it has no methods that take `self` as the first argument, but it does have methods that return `Time`. This was causing the _Free method to not be generated, which was causing a crash when the `Time` object was being freed.
At the same time, I decided to run `cargo fmt`.
Now, when you press F12, it correctly generates a screenshot.
/cc @Flatfingers

Fix crash when triggering screenshot

---

Cargo.lock
engine/lib/phx/Cargo.toml
engine/lib/phx/src/audio/audio.rs
engine/lib/phx/src/audio/mod.rs
engine/lib/phx/src/audio/sound.rs
engine/lib/phx/src/audio/sound_instance.rs
engine/lib/phx/src/physics/physics.rs
engine/lib/phx/src/physics/rigid_body.rs

Some big wins here:
* The newer versions of Rapier has more stable physics calculations (see https://github.com/dimforge/rapier/pull/625)
* The latest version of Kira no longer requires us to handle command buffer full errors, as mentioned in its changelog (see https://github.com/tesselode/kira/blob/main/changelog.md#most-param-changes-are-now-infallible).

Update Rapier and Kira to the latest versions, then update their transitive dependencies.

---

engine/lib/phx/src/engine/engine.rs
engine/lib/phx/src/engine/main_loop.rs
engine/lib/phx/src/logging.rs
script/Main.lua

This means whenever the Rust code triggers a `panic!(...)`, the user will get both a Rust and Lua backtrace.
This works by storing the currently running Lua VM in a ref counted pointer, then making that available in a thread local variable. When a panic occurs, we use that thread local variable to trigger the `HandleEngineError` global function in the Lua VM.

Set up a custom panic hook which invokes the crash handler in Lua.

---

engine/lib/phx/script/ffi_gen/Shader.lua
engine/lib/phx/script/meta/Shader.lua
engine/lib/phx/src/render/gl_bindings.rs
engine/lib/phx/src/render/shader.rs
engine/lib/phx/src/render/shader_state.rs

Fixes a crash introduced by https://github.com/Limit-Theory-Redux/ltheory/pull/295 because we aren't increasing the ref counts of the texture resources

Fix a double free in ShaderState

---

engine/lib/luajit-ffi-gen/src/impl_item/lua_ffi.rs
engine/lib/phx/src/ui/hmgui/mod.rs

Example:
Rust
```rust
/// @overload fun(self: table, eventName: string, ctxTable: table, callbackFunc: function): integer
```
Generated meta:
```lua
---@overload fun(self: table, eventName: string, ctxTable: table, callbackFunc: function): integer
```

Add support for Lua LSP declarations

---

script/UI/DrawEx.lua

Fixes the crash when viewing diagnostics and viewing the system map.

Set the right shader in DrawEx.SimpleRect

---

script/States/App/Tests/EventTest.lua
script/States/Application.lua

This demonstrates a bug where an event is not delivered in some cases. Looks like `preRender` is not called in the first iteration:
```
WARN Context is already current
DEBUG [lua] onPreSim
DEBUG [lua] onPreSim2
DEBUG [lua] onSim
DEBUG [lua] onSim2
DEBUG [lua] onPostSim
DEBUG [lua] onPostSim2
DEBUG [lua] Got my event
DEBUG [lua] onRender
DEBUG [lua] onRender2
DEBUG [lua] onPostRender
DEBUG [lua] onPostRender2
DEBUG [lua] onPreInput
DEBUG [lua] onPreInput2
DEBUG [lua] onInput
DEBUG [lua] onInput2
DEBUG [lua] onPostInput
DEBUG [lua] onPostInput2
```

Add EventTest

---

engine/lib/luajit-ffi-gen/src/impl_item/generate_lua.rs
engine/lib/phx/script/meta/Directory.lua
engine/lib/phx/script/meta/DragAndDropState.lua
engine/lib/phx/script/meta/EventBus.lua
engine/lib/phx/script/meta/EventData.lua
engine/lib/phx/script/meta/EventPayload.lua
engine/lib/phx/script/meta/EventPayloadTable.lua
engine/lib/phx/script/meta/GamepadState.lua
engine/lib/phx/script/meta/Input.lua
engine/lib/phx/script/meta/RigidBody.lua
engine/lib/phx/script/meta/TextStyle.lua
engine/lib/phx/script/meta/Trigger.lua
engine/lib/phx/script/meta/Window.lua

Add `nil` alternative to the Optional types in in the generated meta files.

Add 'nil' alternative for param and return docs in meta

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

GitHub is removing support for Ubuntu 20.04 in Actions, so we need to move to another version. I picked 22.04 as the earliest supported LTS version (so pre-built binaries can run on as many versions of Ubuntu as possible)

Update Ubuntu build from 20.04 to 22.04.

---

.github/workflows/update_license_years.yaml
CONTRIBUTING.md
NOTICE
README.md
UNLICENSE-ORIGINAL.txt

This PR establishes clear documentation about our existing licensing approach for the Limit Theory Redux project, providing transparency without changing any actual license terms. (This is important for legal continuity)
- Added NOTICE file detailing our origin-based licensing approach
- Updated README with licensing information
- Added licensing section to CONTRIBUTING.md
- Clarifies that original Limit Theory content remains under The Unlicense
- Documents the dual Apache 2.0/MIT licensing for new contributions
- Creates a descriptive framework that explains our mixed codebase
- Ensures contributors understand licensing expectations
- Reduces potential legal ambiguity while maintaining practicality

Licensing Clarification for Limit Theory Redux
