Limit-Theory-Redux/ltheory

libphx/include/Window.h
libphx/script/ffi/Window.lua
libphx/script/ffiext/Input.lua
libphx/script/ffiext/Window.lua
libphx/src/Window.cpp
script/States/App/LTheoryRedux.lua
script/States/Application.lua

derp mouse.h is deprecated
requires phx rebuild

feature(mouse): set mouse in input & window class

---

script/Config/App.lua
script/States/App/LTheoryRedux.lua
script/Systems/Overlay/GameView.lua
script/Systems/Overlay/HUD.lua

* Made a proper fix for changing weapon groups.
* Updated GameView to use "system" instead of "world" to be a bit more clear about the context it's using.
* In LTheoryRedux, corrected Config.render.zFar (and zNear) to GameState.render.zFar so that dynamic lighting works again.

GameState Patches 2

---

.gitignore
script/Config/App.lua
script/GameObjects/Components/Material/VisibleMesh.lua
script/Systems/Overlay/GameView.lua
script/Types/GameState.lua

merge after #77 as its dependent on that one
Simple culling for ships & stations

Simple render distances

---

res/shader/fragment/gen/nebula4_weak.glsl

keep this shader around for later

feature(shader): add weak nebula shader

---

script/Enums/HudEnums.lua

- prevent game settings bug / crash
small typo fix for a bug i haven´t noticed, sorry 😞

fix(hud): enums

---

script/Config/App.lua
script/Enums/CameraModes.lua
script/GameObjects/Actions/DockAt.lua
script/States/App/LTheoryRedux.lua
script/Systems/Files/InitFiles.lua
script/Systems/Menus/MainMenu.lua
script/Types/GameState.lua

- add comments to parser
- allow game state table values as subcategories in config file
- save last used camera and reuse after startup
- also temp fixes ships being stuck in docking
if you are switching between branches keep in mind that if u work on a branch that already has these commits you´ll have to update your other working branches to use this new config else it will fail to load the config due to it not recognizing comments

feature(config): config ini parser changes

---

script/Systems/Overlay/HUD.lua

fixes reticle & targets etc not visible
https://discord.com/channels/695088786702336000/695723947307827222/1117233117997052005

fix: quickly fix reticle bug

---

script/States/Application.lua

this is only a quick fix, this should be properly reworked later

fix: quick fix for game over text

---

Cargo.lock
engine/lib/luajit-ffi-gen/readme.md
engine/lib/luajit-ffi-gen/src/impl_item/generate.rs
engine/lib/luajit-ffi-gen/src/impl_item/parse.rs
engine/lib/luajit-ffi-gen/src/impl_item/type_info.rs
engine/lib/luajit-ffi-gen/tests/test_impl.rs
engine/lib/phx/Cargo.toml
engine/lib/phx/script/ffi/Directory.lua
engine/lib/phx/src/system/directory.rs
engine/lib/phx/src/system/timer.rs
script/Systems/Files/InitFiles.lua

Refactor directory module.
Improve Option/Result support in proc macro.

Refactor directory module

---

script/States/App/Tests/TestEcon.lua

fix: economy test

---

engine/lib/phx/src/audio/audio.rs
engine/lib/phx/src/audio/mod.rs
engine/lib/phx/src/audio/sound.rs
script/GameObjects/Entities/Objects/Projectile.lua
script/States/App/Tests/AudioTest.lua

Closes #128 
- enable playing of multiple sounds
- increase command buffer size to 1024
- ignore "command queue full" error

Fix Kira audio

---

script/Config/App.lua
script/States/App/LTheoryRedux.lua
script/Systems/Files/InitFiles.lua
script/Systems/Menus/MainMenu.lua
script/Systems/SFX/MusicPlayer.lua
script/Types/GameState.lua

https://discord.com/channels/695088786702336000/1001732199642578966/1131053700354420777

feature: make main menu theme user configurable

---

script/Systems/Controls/Controls/BackgroundControl.lua

Slows down the background rotation a bit, the current speed gives me a slight headache lol

Slow down background rotation

---

script/States/App/LTheory.lua
script/States/App/LTheoryRedux.lua
script/States/App/Tests/PhysicsTest.lua
script/States/App/Tests/PlanetTest.lua
script/States/App/Tests/ShipTest.lua
script/States/App/Tests/StationTest.lua
script/Systems/Overlay/GameView.lua

fixes: https://github.com/Limit-Theory-Redux/ltheory/issues/150

Pass audio to GameView on creation

---

script/States/App/LTheoryRedux.lua
script/Systems/Menus/MainMenu.lua

Small changes to restore visual behavior of existing UI features now that HmGui layout is working:
1. Simplify the Main Menu (now that HmGui layout is working), extend/improve the comments, and expand the Main Menu buttons vertically again.
2. Individually center the "Cancel" and "OK" buttons in the Settings dialog.
3. Restore the Flight Mode game controls dialog back to the horizontal and vertical center of the game window.

Minor GUI Fixes

---

.github/workflows/pr_build.yaml
.github/workflows/release_build.yaml
build.sh
engine/lib/phx/build.rs
script/Main.lua

fix: PHX_VERSION hardcoded to 0.0.1

---

engine/lib/phx/script/ffi_ext/Sound.lua
engine/lib/phx/script/ffi_gen/Sound.lua
engine/lib/phx/src/audio/sound.rs
script/Systems/SFX/MusicPlayer.lua
script/Types/MusicObject.lua
script/Types/SFXObject.lua

generally fixes setVolume() which was broken/ not implemented
also fix: https://github.com/Limit-Theory-Redux/ltheory/issues/163

fix: set sound volume

---

script/States/App/LTheoryRedux.lua
script/Systems/Menus/MainMenu.lua
script/Systems/SFX/MusicPlayer.lua

fixes the sound toggle in the settings menu

fix: sound toggle in settings menu

---

engine/lib/phx/src/ui/hmgui/container.rs

Apply it for outer widget size instead of inner

Fix percent size calculation

---

script/States/App/LTheoryRedux.lua
script/Systems/Menus/MainMenu.lua

fix: cursor set on settings cancel

---

Cargo.lock
engine/bin/ltr/build.rs
engine/lib/phx/Cargo.toml
engine/lib/phx/build.rs
engine/lib/phx/src/engine/mod.rs
engine/lib/phx/src/physics/trigger.rs
engine/lib/phx/src/render/font.rs

Only one small breaking change in Rapier.

Bump some dependencies, prevent libphx from being rebuilt constantly.

---

engine/lib/phx/script/ffi_gen/HmGui.lua
engine/lib/phx/script/meta/HmGui.lua
engine/lib/phx/src/ui/hmgui/gui.rs
script/Main.lua
script/UI/HmGui/Components/Default/ScrollArea.lua
script/UI/HmGui/Components/Default/Slider.lua
script/UI/HmGui/Views/MainMenu/Settings.lua

Adds a basic slider to the UI default components

feat: add basic slider

---

script/UI/HmGui/Components/Default/Button.lua
script/UI/HmGui/Components/Default/Checkbox.lua
script/UI/HmGui/Components/Default/Switch.lua
script/UI/HmGui/Views/MainMenu/Settings.lua

feat(ui): add switch component

---

engine/lib/phx/script/ffi_common/Shader.lua
engine/lib/phx/script/ffi_common/Tex1D.lua
engine/lib/phx/script/ffi_common/Tex2D.lua
engine/lib/phx/script/ffi_common/Tex3D.lua
engine/lib/phx/script/ffi_gen/Font.lua
engine/lib/phx/script/meta/Font.lua
engine/lib/phx/src/logging.rs
engine/lib/phx/src/math/math.rs
engine/lib/phx/src/render/draw.rs
engine/lib/phx/src/render/font.rs
engine/lib/phx/src/render/gl_bindings.rs
engine/lib/phx/src/render/mesh_compute_ao.rs
engine/lib/phx/src/render/shader.rs
engine/lib/phx/src/render/shader_state.rs
engine/lib/phx/src/render/tex1d.rs
engine/lib/phx/src/render/tex2d.rs
engine/lib/phx/src/render/tex3d.rs
engine/lib/phx/src/render/tex_cube_gen_ir_map.rs
engine/lib/phx/src/render/ui_renderer/layer.rs
engine/lib/phx/src/render/ui_renderer/renderer.rs
engine/lib/phx/src/ui/hmgui/gui.rs
res/shader/fragment/filter/identity.glsl
res/shader/fragment/ui/simple_image.glsl
res/shader/fragment/ui/simple_rect.glsl
script/Render/Renderer.lua
script/States/Application.lua
script/Systems/CommandView/SystemMap.lua
script/Systems/Controls/Controls/DebugControl.lua
script/UI/DrawEx.lua

OpenGL 3+ mandates the use of shaders everywhere, so this PR makes sure we're doing that today.

Remove some usage of fixed function pipeline by incorporating shaders.

---

engine/lib/phx/src/engine/engine.rs
engine/lib/phx/src/engine/mod.rs
engine/lib/phx/src/event_bus/event.rs
engine/lib/phx/src/event_bus/event_data.rs
engine/lib/phx/src/event_bus/frame_stage.rs
engine/lib/phx/src/event_bus/frame_timer.rs
engine/lib/phx/src/event_bus/message_request.rs
engine/lib/phx/src/event_bus/mod.rs
engine/lib/phx/src/lib.rs

Just spitting up the big file a bit.

Split up EventBus module, move it outside of the engine subfolder
